<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:types="http://ffoms.ru/types/3.6/mpiLegalRepresentationSchema" xmlns:tns="http://ffoms.ru/services/3.6/mpiLegalRepresentationServiceWs" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" name="TFOMS_mpiLegalRepresentationServiceWs" targetNamespace="http://ffoms.ru/services/3.6/mpiLegalRepresentationServiceWs">

    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://ffoms.ru/types/3.6/mpiLegalRepresentationSchema" schemaLocation="../xsd/mpiLegalRepresentationSchema.xsd"/>
        </xsd:schema>
    </wsdl:types>


    <wsdl:message name="getLegalRepresentationRequest">
        <wsdl:part element="types:getLegalRepresentationRequest" name="payload"/>
    </wsdl:message>
    <wsdl:message name="getLegalRepresentationResponse">
        <wsdl:part element="types:getLegalRepresentationResponse" name="payload"/>
    </wsdl:message>

    <wsdl:portType name="TFOMS_PortType">
        <wsdl:operation name="getLegalRepresentation">
            <wsdl:input message="tns:getLegalRepresentationRequest"/>
            <wsdl:output message="tns:getLegalRepresentationResponse"/>
        </wsdl:operation>
    </wsdl:portType>

    <wsdl:binding name="TFOMS_SoapBinding" type="tns:TFOMS_PortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="getLegalRepresentation">
            <soap:operation soapAction="http://ffoms.ru/services/tfoms/getLegalRepresentation"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>

    <wsdl:service name="TFOMS_Service">
        <wsdl:documentation>TFOMS Service</wsdl:documentation>
        <wsdl:port binding="tns:TFOMS_SoapBinding" name="TFOMS_Port">
            <soap:address location="http://10.255.87.30:80/api/t-foms/integration/ws/3.6/wsdl/mpiLegalRepresentationServiceWs"/>
        </wsdl:port>
    </wsdl:service>

</wsdl:definitions>